# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import GraphicsLayoutWidget


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1064, 816)
        font = QtGui.QFont()
        font.setPointSize(15)
        Dialog.setFont(font)
        self.comSelectBox = QtWidgets.QComboBox(Dialog)
        self.comSelectBox.setGeometry(QtCore.QRect(870, 70, 151, 31))
        self.comSelectBox.setMaxVisibleItems(6)
        self.comSelectBox.setObjectName("comSelectBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(770, 70, 81, 31))
        self.label.setObjectName("label")
        self.beginButton = QtWidgets.QPushButton(Dialog)
        self.beginButton.setGeometry(QtCore.QRect(880, 260, 141, 41))
        self.beginButton.setObjectName("beginButton")
        self.graphicsView = GraphicsLayoutWidget(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(30, 190, 731, 591))
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 190, 731, 591))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.graph_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.graph_layout.setContentsMargins(0, 0, 0, 0)
        self.graph_layout.setObjectName("graph_layout")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "串口号"))
        self.beginButton.setText(_translate("Dialog", "开始"))



